<?php View::content() ?>
<h1><?= _('Users') ?> <span><?= _('Create') ?></span></h1>
<div>
    <?= Form::open() ?>
    <div class="grid">
    <label>First Name
    <?= Form::text('data.first_name', 'required') ?> 
    </label>

    <label>Last Name
    <?= Form::text('data.last_name', 'required') ?> 
    </label>
    </div>
    <label>Email
    <?= Form::email('data.email', 'required') ?> 
    </label>

    <?= Form::submit(_('Save')) ?>
    <?= Form::close() ?>
</div>
<div class="actions">
        <a href="../" role="button"><?= _('List') ?></a>
</div> 