<?php

/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.
 * 
 * Paginador "digg" para aplicaciones
 *
 * Parametros del paginador:
 *   page: objeto obtenido al invocar al paginador
 *   show: numero de paginas que se mostraran en el paginador
 *   url: url para la accion que efectua la paginacion, por defecto "module/controller/page/"
 *        y se envia por parametro el numero de pagina
 *
 * @category    Kumbia
 * @package     Partials
 * @subpackage  Paginators
 *
 * @copyright  Copyright (c) 2005 - 2020 KumbiaPHP Team (http://www.kumbiaphp.com)
 * @license    https://github.com/KumbiaPHP/KumbiaPHP/blob/master/LICENSE   New BSD License
 */

$url = $url ?? Router::get('controller_path') . '/page';
$show = $show ?? 10;

$half = floor($show / 2);

//Calculando el inicio de paginador centrado
if ($page->page() <= $half) {
    $start = 1;
} elseif (($page->totalPages() - $page->page()) < $half) {
    $start = $page->totalPages() - $show + 1;
    if ($start < 1) {
        $start = 1;
    }
} else {
    $start = $page->page() - $half;
}
$last = false;
if ($start === $page->totalPages()) {
    if ($start - 1 > 0) {
        $start -= 1;
    }

    $last = true;
}
?>

<nav class="paginator">
    <?php if ($page->prevPage() === 1) {
        echo Html::link("$url/",  _('Prev'), 'rel="prev"');
    }
    //se coloca el link sin número de página para la página 1
    elseif ($page->prevPage()) {
        echo Html::link("$url/$page->prevPage()/", _('Prev'), 'rel="prev"');
    }
    ?>

    <?php if ($start === 1) { //se coloca el link sin número de página para la página 1
        $start = 2;
        $show -= 1;
        echo $page->page() === 1 ? "<strong>1</strong>" : Html::link("$url/", '1');
    } ?>

    <?php for ($i = $start; $i <= $page->totalPages() && $i < ($start + $show); $i++) : ?>
        <?= $i === $page->page() ? "<strong>$i</strong>" : Html::link("$url/$i/", $i ) ?>
    <?php endfor ?>

    <?php if ($page->totalPages() > $i) : ?>
        <?php if ($page->totalPages() > ($i + 1)) : ?>
            ...
        <?php endif ?>

        <?php $i = $page->totalPages() - 1 ?>
        <?= Html::link("$url/$i/", $i) ?>
        <?= Html::link("$url/{$page->totalPages()}/", $page->totalPages()) ?>
    <?php elseif ($i === $page->totalPages()) : ?>
        <?php if ($last) : ?>
            <?= "<strong>$i</strong>" ?>
        <?php else : ?>
            <?= Html::link("$url/$i/", $i) ?>
        <?php endif ?>
    <?php endif ?>

    <?php if ($page->nextPage()) {
        echo Html::link("$url/{$page->nextPage()}/", _('Next'), 'rel="next"');
    } ?>
</nav> 