<section id="home">
    <h1>Welcome to Koot</h1>
    <p>Koot is your go-to community backend solution, built on the robust KumbiaPHP framework.</p>
</section>

<section id="features">
    <h2>Features</h2>

    <div class="grid">
        <article>
            <picture>
                <source type="image/avif" srcset="/img/welcome/user_management.avif">
                <img src="/img/welcome/user_management.png" alt="Diverse Group of Avatars Representing Users" class="responsive">
            </picture>

            <h3>User Management</h3>
            <p>Handle user registrations, logins, and profiles efficiently.</p>
        </article>

        <article>
            <picture>
                <source type="image/avif" srcset="/img/welcome/role_based_access_control.avif">
                <img src="/img/welcome/role_based_access_control.png" alt="Hierarchical Structure of User Roles" class="responsive">
            </picture>

            <h3>Role-Based Access Control</h3>
            <p>Define roles and assign them to users for granular access control.</p>
        </article>

        <article>
            <picture>
                <source type="image/avif" srcset="/img/welcome/resource_management.avif">
                <img src="/img/welcome/resource_management.png" alt="Digital Library of Resources" class="responsive">
            </picture>

            <h3>Resource Management</h3>
            <p>Manage your application's resources with ease.</p>
        </article>

        <article>
            <picture>
                <source type="image/avif" srcset="/img/welcome/permission_handling.avif">
                <img src="/img/welcome/permission_handling.png" alt="Security Themed Image for Permissions" class="responsive">
            </picture>

            <h3>Permission Handling</h3>
            <p>Fine-tune permissions for different user roles.</p>
        </article>
    </div>
</section>

<section id="about">
    <h2>About Koot</h2>
    <p>Koot is designed to streamline backend development, minimizing repetitive tasks and focusing on unique features of your applications.</p>
</section>


<section id="contact">
    <h2>Contact Us</h2>
    <p>Have questions or want to get involved? <a href="https://slack.kumbiaphp.com">Chat us</a> or visit our <a href="https://github.com/kumbiaphp/koot">GitHub page</a>.</p>
</section>