<div id="scaffold">
    <?php View::content() ?>
    <h1><?= ucwords("$model") ?> <span><?= _('List') ?></span></h1>
    <div class="actions">
        <?= Html::linkAction("create/", _('Create'), 'class="btn btn-primary"') ?>
    </div>
    <?php if (isset($data) && (count($data) > 0)) : ?>
        <?php $path = $action_name === 'page' ? '../../' : ''; ?>
        <table class="t">
            <caption><?= ucwords("$model") ?></caption>
            <thead>
                <tr>
                    <?php foreach ($data->getAlias() as $alias) : ?>
                        <th scope="col"><?= $alias ?></th>
                    <?php endforeach ?>
                    <th scope="col"><?= _('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $item) : ?>
                    <tr>
                        <?php foreach ($data->getFields() as $field) : ?>
                            <td><?= h($item->$field) ?></td>
                        <?php endforeach ?>
                        <td>
                            <a href="<?= "{$path}show/$item->id" ?>" class="btn btn-primary"><?= _('Show') ?></a>
                            <a href="<?= "{$path}edit/$item->id" ?>" class="btn btn-warning"><?= _('Edit') ?></a>
                            <a href="<?= "{$path}delete/$item->id" ?>" class="del btn btn-danger" title="<?= _('Are you sure you want to delete?') ?>" onclick="return confirm('<?= _('Are you sure?') ?>');"><?= _('Delete') ?></a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php View::partial('paginators/digg', false, ['page' => $data, 'url' => Router::get('controller_path') . '/page']) ?>

    <?php else : // Si no hay items
    ?>
        <h2>No hay ningún registro</h2>
    <?php endif ?>
</div>