<div id="scaffold">
    <?php View::content() ?>
    <h1><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
    <div class="actions">
        <?= Html::linkAction("create/", 'Crear registro', 'class="btn btn-primary"') ?>
    </div>
    <?php //var_dump($data->getAlias()) ?>
    <?php if (isset($data) && (count($data) > 0)) : ?>
        <table class="t">
            <thead>
                <tr>
                    <?php foreach ($data->getAlias() as $alias) : ?>
                        <th><?= $alias ?></th>
                    <?php endforeach ?>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $item) : ?>
                    <tr>
                        <?php foreach ($data->getFields() as $field) : ?>
                            <td><?= h($item->$field) ?></td>
                        <?php endforeach ?>
                        <td><?= Html::linkAction("ver/$item->id", 'Ver') ?> |
                            <?= Html::linkAction("editar/$item->id", 'Editar') ?> |
                            <?= Html::linkAction("borrar/$item->id", 'Borrar', 'onclick="return confirm(\'¿Está seguro?\')"') ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php View::partial('paginators/digg', false, array('page' => $data, 'url' => Router::get('controller_path') . '/index')) ?>

    <?php else : // Si no hay items
    ?>
        <h2>No hay ningún registro</h2>
    <?php endif ?>
</div>