<div id="scaffold">
    <?php View::content() ?>
    <?php if ($data) : ?>
        <h1><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
        <ul>
            <?php foreach ($data->getFields() as $key => $field) : ?>
                <li><strong><?= $data->getAlias()[$key] ?> :</strong> <?= h($data->$field) ?></li>
            <?php endforeach ?>
        </ul>

        <div class="actions">
            <a href="../page" class="btn btn-default">Listado</a>
            <a href="../create/" class="btn btn-primary">Crear registro</a>
            <a href="../edit/<?= $data->id ?>" class="btn btn-warning">Editar</a>
            <a class="del btn btn-danger" title="¿Seguro que quiere borrar?" href="../borrar/<?= $data->id ?>" onclick="return confirm('¿Está seguro?');">Borrar</a>
        </div>
    <?php else : ?>
        <?php http_response_code(404) ?>
        <h1>_('Record not found')</h1>
        <div class="actions">
            <a href="../page">Listado</a>
            <a href="../create/">Crear registro</a>
        </div>
    <?php endif ?>
</div>