<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>Koot Fast App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/css/koot.min.css?<?= filemtime('css/koot.min.css') ?>">
</head>
<body>
<div class="container">
  <header>
    <nav>
      <ul>
        <li><a href="#"><?= Html::img('kumbiaphp.svg', 'KumbiaPHP logo') ?></a</li>
      </ul>
      <ul>
        <li><a href="#">Link</a></li>
        <li><a href="#" role="button">Link</a></li>
        <li>App: <strong>Koot</strong> (<?= PRODUCTION ? 'Production' : 'Development' ?>)</li>
      </ul>
    </nav>
  </header>
  <?php View::content() ?>
  <?php View::partial('kumbia/footer') ?>
</div>
</body>
</html>
