-- MySQL Script generated by MySQL Workbench
-- Sun May 10 19:28:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema koot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `koot`;

-- -----------------------------------------------------
-- Schema koot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koot` DEFAULT CHARACTER SET utf8;
USE `koot`;

-- -----------------------------------------------------
-- Table `koot`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koot`.`permissions`
(
    `id`           INT NOT NULL AUTO_INCREMENT,
    `roles_id`     INT NOT NULL,
    `resources_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_permissions__roles`
        FOREIGN KEY (`roles_id`)
            REFERENCES `koot`.`roles` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_permissions__resources`
        FOREIGN KEY (`resources_id`)
            REFERENCES `koot`.`resources` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_permissions_roles_idx` ON `koot`.`permissions` (`roles_id` ASC);

CREATE INDEX `fk_permissions_resources_idx` ON `koot`.`permissions` (`resources_id` ASC);


-- -----------------------------------------------------
-- Table `koot`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koot`.`resources`
(
    `id`          INT             NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(127)    NOT NULL,
    `description` VARCHAR(255)    NULL,
    `url`         VARCHAR(255)    NOT NULL,
    `module`      VARCHAR(45)     NULL,
    `controller`  VARCHAR(45)     NOT NULL,
    `action`      VARCHAR(45)     NOT NULL,
    `status`      ENUM ('0', '1') NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

CREATE UNIQUE INDEX `resources_name_UNIQUE` ON `koot`.`resources` (`name` ASC);

CREATE UNIQUE INDEX `resources_url_UNIQUE` ON `koot`.`resources` (`url` ASC);


-- -----------------------------------------------------
-- Table `koot`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koot`.`roles`
(
    `id`     INT             NOT NULL AUTO_INCREMENT,
    `name`   VARCHAR(45)     NULL,
    `status` ENUM ('0', '1') NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koot`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koot`.`users`
(
    `id`         INT             NOT NULL AUTO_INCREMENT,
    `email`      VARCHAR(255)    NOT NULL,
    `password`   VARCHAR(255)    NOT NULL,
    `first_name` VARCHAR(255)    NULL,
    `last_name`  VARCHAR(255)    NULL,
    `status`     ENUM ('0', '1') NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

CREATE UNIQUE INDEX `users_email_UNIQUE` ON `koot`.`users` (`email` ASC);


-- -----------------------------------------------------
-- Table `koot`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koot`.`users_roles`
(
    `id`       INT NOT NULL AUTO_INCREMENT,
    `users_id` INT NOT NULL,
    `roles_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_users_roles__users`
        FOREIGN KEY (`users_id`)
            REFERENCES `koot`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_users_roles__roles`
        FOREIGN KEY (`roles_id`)
            REFERENCES `koot`.`roles` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

CREATE INDEX `fk_users_roles_users_idx` ON `koot`.`users_roles` (`users_id` ASC);

CREATE INDEX `fk_users_roles_roles_idx` ON `koot`.`users_roles` (`roles_id` ASC);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
