<?php View::content() ?>
<h1><?= ucwords("$model") ?> <span><?= _('Create') ?></span></h1>
<div class="row">
    <div class="col-8 offset-2">
        <?= Form::open(); ?>
        <label for="data_name">Name</label>
        <?= Form::text('data.name', 'required') ?>
        <label for="data_description">Description</label>
        <?= Form::text('data.description') ?>
        <label for="data_module">Module</label>
        <?= Form::text('data.module') ?>
        <label for="data_controller">Controller</label>
        <?= Form::text('data.controller', 'required') ?>
        <label for="data_action">Action</label>
        <?= Form::text('data.action', 'required') ?>
        <label for="data_url">URL</label>
        <?= Form::text('data.url', 'required') ?>
        <?= Form::submit(_('Save'), 'class="btn btn-primary"') ?>
        <?= Form::close(); ?>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <a href="../" class="btn btn-default"><?= _('List'); ?></a>
    </div>
</div>